--- # install java and download & install jenkins playbook
- hosts: webservers
  become: yes


  tasks: 
    - name: install java on redhat
      yum:
        name: java
        state: present

    - name: install wget command
      yum:
        name: wget
        state: installed

    - name: download jenkins 
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: download key of jenkins s/w
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key


    - name: install jenkins s/w
      yum:
        name: jenkins
        state: installed


    - name: start jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes



