--- 
- name: install java, download & install tomcat
  hosts: all
  become: yes

  tasks:
    - name: install java on redhat
      ansible.builtin.yum:
        name: java
        state: present
      when: ansible_os_family == "RedHat"


    - name: install java on debian
      apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian" 


    - name: download apache tomcat s/w
      ansible.builtin.get_url: 
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.97/bin/apache-tomcat-8.5.97.tar.gz
        dest: /opt



    - name: extract tomcat s/w
      unarchive: 
        src: /opt/apache-tomcat-8.5.97.tar.gz 
        dest: /opt
        remote_src: yes


    - name: providing executable permission
      file:
        path: /opt/apache-tomcat-8.5.97/bin/startup.sh
        mode: 0777

    - name: start tomcat service/execute script 
      shell: nohup ./startup.sh
      args:
        chdir: /opt/apache-tomcat-8.5.97/bin



# nohup meaning it has to start the tomact even if change the folder too.
# chdir means change directory 
