--- # My tasks playbook 
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: Install httpd s/w into webservers
      action: yum name=http state=installed
      ignore_errors: yes

 
     
     
        #adding an ignore error task and commenting below task

#  tasks:
#    - name: Install httpd s/w into webservers
#      action: yum name=httpd state=installed
 


