--- # more than one task playbook
- hosts: webservers
  become: true


  tasks:
    - name: remove package
      yum:
        name: httpd
        state: absent

          # this task will throw error because first we are removing s/w the we are stoping service.

    - name: stop service
      service:
        name: httpd
        state: stopped


# below part is commenting because above part need to test

#  tasks:
#   - name: Installing package
#     yum:
#       name: httpd
#       state: installed



#   - name: start service
#     service:
#        name: httpd
#        state: started

